site_name: Medusa Docs
site_description: A documentation for Medusa programming language. Work in progress.
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - rust
extra_javascript:
  - hljs.mds.js
